<?php

/**
 * This is the model base class for the table "simulacao_equipamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SimulacaoEquipamento".
 *
 * Columns in table "simulacao_equipamento" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $simulacao
 * @property integer $equipamento
 *
 */
abstract class BaseSimulacaoEquipamento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'simulacao_equipamento';
    }

    public static function representingColumn() {
        return array(
            'simulacao',
            'equipamento',
        );
    }

    public function rules() {
        return array(
            array('simulacao, equipamento', 'required'),
            array('simulacao, equipamento', 'numerical', 'integerOnly'=>true),
            array('simulacao, equipamento', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'simulacao' => Yii::t('app', 'Simulacao'),
                'equipamento' => Yii::t('app', 'Equipamento'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('simulacao', $this->simulacao);
        $criteria->compare('equipamento', $this->equipamento);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}