<?php

/**
 * This is the model base class for the table "utilizador".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Utilizador".
 *
 * Columns in table "utilizador" available as properties of the model,
 * followed by relations of table "utilizador" available as properties of the model.
 *
 * @property integer $id
 * @property string $nome
 * @property string $password
 * @property integer $contacto
 *
 * @property Cliente[] $clientes
 * @property Profissional[] $profissionals
 */
abstract class BaseUtilizador extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'utilizador';
    }

    public static function representingColumn() {
        return 'nome';
    }

    public function rules() {
        return array(
            array('nome, password, contacto', 'required'),
            array('contacto', 'numerical', 'integerOnly'=>true),
            array('nome, password', 'length', 'max'=>50),
            array('id, nome, password, contacto', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'clientes' => array(self::HAS_MANY, 'Cliente', 'utilizador'),
            'profissionals' => array(self::HAS_MANY, 'Profissional', 'utilizador'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nome' => Yii::t('app', 'Nome'),
                'password' => Yii::t('app', 'Password'),
                'contacto' => Yii::t('app', 'Contacto'),
                'clientes' => null,
                'profissionals' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nome', $this->nome, true);
        $criteria->compare('password', $this->password, true);
        $criteria->compare('contacto', $this->contacto);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}