<?php

/**
 * This is the model base class for the table "visita_equipamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VisitaEquipamento".
 *
 * Columns in table "visita_equipamento" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $visita
 * @property integer $equipamento
 *
 */
abstract class BaseVisitaEquipamento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'visita_equipamento';
    }

    public static function representingColumn() {
        return array(
            'visita',
            'equipamento',
        );
    }

    public function rules() {
        return array(
            array('visita, equipamento', 'required'),
            array('visita, equipamento', 'numerical', 'integerOnly'=>true),
            array('visita, equipamento', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'visita' => Yii::t('app', 'Visita'),
                'equipamento' => Yii::t('app', 'Equipamento'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('visita', $this->visita);
        $criteria->compare('equipamento', $this->equipamento);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}