<?php

/**
 * This is the model base class for the table "visita".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Visita".
 *
 * Columns in table "visita" available as properties of the model,
 * followed by relations of table "visita" available as properties of the model.
 *
 * @property integer $id
 * @property string $data
 * @property integer $empresa
 * @property integer $profissional
 *
 * @property Empresa $empresa0
 * @property Profissional $profissional0
 * @property Equipamento[] $equipamentos
 */
abstract class BaseVisita extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'visita';
    }

    public static function representingColumn() {
        return 'data';
    }

    public function rules() {
        return array(
            array('data, empresa, profissional', 'required'),
            array('empresa, profissional', 'numerical', 'integerOnly'=>true),
            array('id, data, empresa, profissional', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'empresa0' => array(self::BELONGS_TO, 'Empresa', 'empresa'),
            'profissional0' => array(self::BELONGS_TO, 'Profissional', 'profissional'),
            'equipamentos' => array(self::MANY_MANY, 'Equipamento', 'visita_equipamento(visita, equipamento)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'data' => Yii::t('app', 'Data'),
                'empresa' => Yii::t('app', 'Empresa'),
                'profissional' => Yii::t('app', 'Profissional'),
                'empresa0' => null,
                'profissional0' => null,
                'equipamentos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('data', $this->data, true);
        $criteria->compare('empresa', $this->empresa);
        $criteria->compare('profissional', $this->profissional);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}