<?php

/**
 * This is the model base class for the table "equipamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Equipamento".
 *
 * Columns in table "equipamento" available as properties of the model,
 * followed by relations of table "equipamento" available as properties of the model.
 *
 * @property integer $id
 * @property string $nome
 * @property integer $potencia
 * @property integer $horas
 * @property integer $quantidade
 * @property double $consumo
 *
 * @property Potencia $potencia0
 * @property Simulacao[] $simulacaos
 */
abstract class BaseEquipamento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'equipamento';
    }

    public static function representingColumn() {
        return 'nome';
    }

    public function rules() {
        return array(
            array('nome, potencia, horas, quantidade, consumo', 'required'),
            array('potencia, horas, quantidade', 'numerical', 'integerOnly'=>true),
            array('consumo', 'numerical'),
            array('nome', 'length', 'max'=>50),
            array('id, nome, potencia, horas, quantidade, consumo', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'potencia0' => array(self::BELONGS_TO, 'Potencia', 'potencia'),
            'simulacaos' => array(self::MANY_MANY, 'Simulacao', 'simulacao_equipamento(equipamento, simulacao)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nome' => Yii::t('app', 'Nome'),
                'potencia' => Yii::t('app', 'Potencia'),
                'horas' => Yii::t('app', 'Horas'),
                'quantidade' => Yii::t('app', 'Quantidade'),
                'consumo' => Yii::t('app', 'Consumo'),
                'potencia0' => null,
                'simulacaos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nome', $this->nome, true);
        $criteria->compare('potencia', $this->potencia);
        $criteria->compare('horas', $this->horas);
        $criteria->compare('quantidade', $this->quantidade);
        $criteria->compare('consumo', $this->consumo);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}