<?php

/**
 * This is the model base class for the table "simulacao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Simulacao".
 *
 * Columns in table "simulacao" available as properties of the model,
 * followed by relations of table "simulacao" available as properties of the model.
 *
 * @property integer $id
 * @property integer $empresa
 * @property string $data
 * @property double $consumo_total
 *
 * @property Empresa $empresa0
 * @property Equipamento[] $equipamentos
 */
abstract class BaseSimulacao extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'simulacao';
    }

    public static function representingColumn() {
        return 'data';
    }

    public function rules() {
        return array(
            array('empresa, data, consumo_total', 'required'),
            array('empresa', 'numerical', 'integerOnly'=>true),
            array('consumo_total', 'numerical'),
            array('id, empresa, data, consumo_total', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'empresa0' => array(self::BELONGS_TO, 'Empresa', 'empresa'),
            'equipamentos' => array(self::MANY_MANY, 'Equipamento', 'simulacao_equipamento(simulacao, equipamento)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'empresa' => Yii::t('app', 'Empresa'),
                'data' => Yii::t('app', 'Data'),
                'consumo_total' => Yii::t('app', 'Consumo Total'),
                'empresa0' => null,
                'equipamentos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('empresa', $this->empresa);
        $criteria->compare('data', $this->data, true);
        $criteria->compare('consumo_total', $this->consumo_total);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}